/**
 * THIS FILE IS GENERATED by branchkit.
 * Do not edit this file directly. Edit the version files instead (e.g., Example1.v1.tsx).
 * To stop versioning this component, run: branchkit promote Example1 <version-id>
 */
import { ForkedComponent } from "/branchkit";
import { VERSIONS } from "./Example1.versions";

export default function Example1(props: any) {
  return <ForkedComponent id="Example1" versions={VERSIONS} props={props} />;
}

export { VERSIONS };
