/**
 * THIS FILE IS GENERATED by branchkit.
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx branchkit promote ContactCard <version-id>
 */
import ContactCardV1 from "./ContactCard.v1"
import ContactCardV2 from "./ContactCard.v2"
export const VERSIONS = {
  "v1": {
    render: ContactCardV1,
    label: "",
  },
  "v2": {
    render: ContactCardV2,
    label: "",
  },
}
