"use client"

/**
 * THIS FILE IS GENERATED by branchkit.
 * Do not edit this file directly. Edit the version files instead (e.g., DashboardContent.v1.tsx).
 * To stop versioning this component, run: npx branchkit promote DashboardContent <version-id>
 */
import { ForkedComponent } from "branchkit"
import { VERSIONS } from "./DashboardContent.versions"

export default function DashboardContent(props: any) {
  return (
    <ForkedComponent
      id="DashboardContent"
      versions={VERSIONS}
      props={props}
    />
  )
}

export { VERSIONS }
